language: r
sudo: required

bioc_packages:
  - snpStats

r_binary_packages:
  - knitr

apt_packages:
  - latex-xcolor
  - texlive-fonts-extra
  - tff-inconsolata

notifications:
  email:
    - oualkacha.karim@uqam.ca
