language: r
sudo: required

# the check throws an error because it can't open some graphic device
warnings_are_errors: false

bioc_packages:
  - snpStats

r_binary_packages:
  - knitr

apt_packages:
  - latex-xcolor
  - texlive-fonts-extra
  - ttf-inconsolata
  - texinfo
  - texlive-fonts-recommended

notifications:
  email:
    - oualkacha.karim@uqam.ca
